### ISSUE TITLE
Hitting escape in ModConfigGui causes crash 

### ISSUE THREAD

**Issue by Sk1er** [HyperiumClient/Hyperium#47]
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at net.minecraft.client.gui.GuiMainMenu.initGui(GuiMainMenu.java:780)
	at net.minecraft.client.gui.GuiScreen.setWorldAndResolution(GuiScreen.java:539)
	at net.minecraft.client.Minecraft.displayGuiScreen(Minecraft.java:3512)
	at net.minecraft.client.gui.GuiScreen.keyTyped(GuiScreen.java:100)
	at cc.hyperium.gui.ModConfigGui.keyTyped(ModConfigGui.java:162)
	at net.minecraft.client.gui.GuiScreen.handleKeyboardInput(GuiScreen.java:622)
	at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:573)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1733)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1061)
	at net.minecraft.client.Minecraft.run(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(Main.java:113)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
	at GradleStart.main(GradleStart.java:26)

**Comment by Sk1er** [comment]
https://sk1er.exposed/22.37.30-28.02.18.gif
