### ISSUE TITLE
Crash on Launch, Mac

### ISSUE THREAD

**Issue by MGelgor** [HyperiumClient/Hyperium#642]
I downloaded it for the first time, on launch it gives a crash screen.
I just press the play button and it gives this screen without showing a welcome screen.
iMac Late 2013
Mac OS Mojave 10.14
Hyperium 1.0.2

java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
Caused by: java.lang.NoClassDefFoundError: adm
	at net.minecraft.client.main.Main.main(SourceFile:41)
	... 6 more
Caused by: java.lang.ClassNotFoundException: adm
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:179)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:521)
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:267)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:165)
	... 9 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [mixins.hyperium.json:world.IMixinWorld] from phase [DEFAULT] in config [mixins.hyperium.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinError(MixinTransformer.java:779)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinApplyError(MixinTransformer.java:732)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:513)
	... 12 more
Caused by: org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException: No candidates were found matching ￄﾱsChunkLoaded(IIZ)Z in adm for mixins.hyperium.json:world.IMixinWorld->@Invoker[METHOD_PROXY]::callIsChunkLoaded(IIZ)Z
	at org.spongepowered.asm.mixin.gen.AccessorInfo.findTarget(AccessorInfo.java:382)
	at org.spongepowered.asm.mixin.gen.InvokerInfo.findTargetMethod(InvokerInfo.java:62)
	at org.spongepowered.asm.mixin.gen.InvokerInfo.locate(InvokerInfo.java:58)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.generateAccessors(MixinTargetContext.java:1214)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyAccessors(MixinApplicatorStandard.java:918)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:308)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:267)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509)
	... 12 more

**Comment by RDIL** [comment]
Hi,
What version of Hyperium are you using?

**Comment by MGelgor** [comment]
1.0.2, latest version. Ingame it's 1.8.9

**Comment by RDIL** [comment]
Try using our 1.1 betas @MGelgor .  They can be found [here](../../releases).

**Comment by MGelgor** [comment]
Am I supposed to remove the version I am using?

**Comment by RDIL** [comment]
The installer will do that on its own @MGelgor

**Comment by MGelgor** [comment]
It still crashes

**Comment by RDIL** [comment]
@MGelgor try downloading Java 8
https://download.oracle.com/otn-pub/java/jdk/8u201-b09/42970487e3af4f5aa5bca3f542482c60/jdk-8u201-macosx-x64.dmg

**Comment by asbyth** [comment]
use 2563, latest doesnt work on mac

**Comment by asbyth** [comment]
fixed in the next version, should be released soon
