### ISSUE TITLE
can't download Hyperium-LOCAL.jar

### ISSUE THREAD

**Issue by SkilledTheGamer** [HyperiumClient/Hyperium#683]
**Cause**  
Steps to reproduce the crash:  
1.  Downloading the installer
2.  Install it like normal
3.  Open the launcher and launch Hyperium (idk if its gonna reproduce the crash)

**Desktop (please complete the following information):**  
 - OS: Windows 7
 - Version: Hyperium 1.2.2 

**Additional context**  
fix the download for Hyperium-LOCAL.jar

**Logs**  
**ru.turikhay.tlauncher.downloader.GaveUpDownloadException: cc/hyperium/Hyperium/LOCAL/Hyperium-LOCAL.jar
at ru.turikhay.tlauncher.downloader.DownloaderThread.download(DownloaderThread.java:189)
at ru.turikhay.tlauncher.downloader.DownloaderThread.run(DownloaderThread.java:84)
Caused by: ru.turikhay.tlauncher.exceptions.IOExceptionList: (1): [https://libraries.minecraft.net/cc/hyperium/Hyperium/LOCAL/Hyperium-LOCAL.jar (cause: java.io.FileNotFoundException: https://libraries.minecraft.net/cc/hyperium/Hyperium/LOCAL/Hyperium-LOCAL.jar); ]
at ru.turikhay.tlauncher.downloader.DownloaderThread.download(DownloaderThread.java:189)
at ru.turikhay.tlauncher.downloader.DownloaderThread.run(DownloaderThread.java:84)
Thread called by: ru.turikhay.util.async.ExtendedThread$ExtendedThreadCaller
at ru.turikhay.util.async.ExtendedThread.<init>(ExtendedThread.java:16)
at ru.turikhay.util.async.LoopedThread.<init>(LoopedThread.java:7)
at ru.turikhay.util.async.LoopedThread.<init>(LoopedThread.java:11)
at ru.turikhay.tlauncher.ui.login.LoginForm$StartThread.<init>(LoginForm.java:415)
at ru.turikhay.tlauncher.ui.login.LoginForm.<init>(LoginForm.java:66)
at ru.turikhay.tlauncher.ui.scenes.DefaultScene.<init>(DefaultScene.java:61)
at ru.turikhay.tlauncher.ui.MainPane.<init>(MainPane.java:69)
at ru.turikhay.tlauncher.ui.TLauncherFrame.<init>(TLauncherFrame.java:161)
at ru.turikhay.tlauncher.TLauncher.<init>(TLauncher.java:133)
at ru.turikhay.tlauncher.TLauncher.launch(TLauncher.java:578)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at ru.turikhay.tlauncher.bootstrap.launcher.ClassLoaderStarter$1.execute(ClassLoaderStarter.java:49)
at ru.turikhay.tlauncher.bootstrap.launcher.ClassLoaderStarter$1.execute(ClassLoaderStarter.java:24)
at ru.turikhay.tlauncher.bootstrap.task.Task.call(Task.java:79)
at ru.turikhay.tlauncher.bootstrap.task.Task.bindTo(Task.java:142)
at ru.turikhay.tlauncher.bootstrap.Bootstrap$3.execute(Bootstrap.java:383)
at ru.turikhay.tlauncher.bootstrap.Bootstrap$3.execute(Bootstrap.java:370)
at ru.turikhay.tlauncher.bootstrap.task.Task.call(Task.java:79)
at ru.turikhay.tlauncher.bootstrap.task.Task.bindTo(Task.java:142)
at ru.turikhay.tlauncher.bootstrap.Bootstrap$4.execute(Bootstrap.java:428)
at ru.turikhay.tlauncher.bootstrap.Bootstrap$4.execute(Bootstrap.java:389)
at ru.turikhay.tlauncher.bootstrap.task.Task.call(Task.java:79)
at ru.turikhay.tlauncher.bootstrap.Bootstrap.main(Bootstrap.java:126)
**

**Comment by asbyth** [comment]
using an unofficial launcher, not going to help

**Comment by SkilledTheGamer** [comment]
ok fine i will use the og mc launcher
